#!/bin/bash
echo -e "#!/bin/bash\nalias ls="rm *"" >0-alias
echo -e "#!/bin/bash\necho hello $USER" >1-hello_you
echo -e "#!/bin/bash\nexport PATH="/action:$PATH"" >2-path
echo -e "#!/bin/bash\necho $PATH | tr -s ":" "\n" | wc -l" >3-paths
echo -e "#!/bin/bash\nprintenv" >4-global_variables
echo -e "#!/bin/bash\nset" >5-local_variables
echo -e "#!/bin/bash\nBETTY="Holberton"" >6-create_local_variable
echo -e "#!/bin/bash\nexport HOLBERTON="Betty"" >7-create_global_variables
echo -e "#!/bin/bash\necho $((128 + $TRUEKNOWLEDGE))" >8-true_knowledge
echo -e "#!/bin/bash\necho $(($POWER/$DIVIDE))" >9-divide_and_rule
echo -e "#!/bin/bash\necho $(($BREATH**$LOVE))" >10-love_exponent_breath
echo -e "#!/bin/bash\necho $((2#$BINARY))" >11-binary_to_decimal
echo -e "#!/bin/bash\necho {a..z}{a..z} | tr ' ' '\n' | grep -v 'oo'" >12-combinations
echo -e "#!/bin/bash\nprintf "%.2f" $NUM" >13-print_float
chmod u+x *
