#!/bin/bash
echo -e "#!/bin/bash\npwd" >>0-current_working_directory
echo -e "#!/bin/bash\nls" >>1-listit
echo -e "#!/bin/bash\ncd" >>2-bring_me_home
echo -e "#!/bin/bash\nls -l" >>3-listfiles
echo -e "#!/bin/bash\nls- la" >>4-listmorefiles
echo -e "#!/bin/bash\nls -na" >>5-listfilesdigitonly
echo -e "#!/bin/bash\nmkdir /tmp/holberton/" >>6-firstdirectory
echo -e "#!/bin/bash\nmv /tmp/betty /tmp/holberton/" >>7-movethatfile
echo -e "#!/bin/bash\nrm /tmp/holberton/betty" >>8-firstdelete
echo -e "#!/bin/bash\nrmdir /tmp/holberton/" >>9-firstdirdeletion
echo -e "#!/bin/bash\ncd-" >>10-back
echo -e "#!/bin/bash\nls -al . .. /boot/" >>11-lists
echo -e "#!/bin/bash\nfile /tmp/iamafile" >>12-file_type
echo -e "#1/bin/bash\nls -s /bin/ls __ls__" >>13-symbolic_link
echo -e "#!/bin/bash\ncp -rua *.html ../" >>14-copy_html
chmod u+x *
cd..
git status && git add --all && git commit -m "Almost there" && git push origin master